# Generated by Django 6.0.5 on 2026-06-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
