# Generated by Django 6.0.5 on 2026-06-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_otp_customuser_email_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
