# Generated by Django 6.0.5 on 2026-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/logos/'),
        ),
    ]
